Correct metadata dependencies
Role fails to install via ansible-galaxy due to incorrect nesting
of the `dependencies` key

- openstack-ansible-galaxy.openstack-glance was installed successfully
Traceback (most recent call last):
  File "/usr/local/Cellar/ansible/1.9.2/libexec/bin/ansible-galaxy", line 959, in <module>
    main()
  File "/usr/local/Cellar/ansible/1.9.2/libexec/bin/ansible-galaxy", line 953, in main
    fn(args, options, parser)
  File "/usr/local/Cellar/ansible/1.9.2/libexec/bin/ansible-galaxy", line 845, in execute_install
    role_dependencies = role_data['dependencies']
KeyError: 'dependencies'